### PR TITLE
Reboot Gaia as a Girder plugin, plus 'SimpleWPS' functionality

### PR DESCRIPTION
**Pull request by mbertrand**
This branch starts Gaia from scratch as a Girder plugin, and adds a 'SimpleWPS' functionality that serves as a proxy between Girder and a WPS server: it accepts simple JSON objects in the request body for a subset of available WPS processes, converts the JSON to standard WPS XML format, passes on the request to the WPS server, and sends the response back to the client.  If 'return_xml: true' is passed in the request JSON body, Gaia will return back the generated XML only and not send the request on to the WPS server.

The following processes are currently supported: vec:Query, vec:Clip, ras:RasterZonalStatistics, gs:CollectGeometries, gs:cropCoverage.

TODO: Support more WPS processes; improve OWSlib's WPS XML generation and use that instead of custom code here.

### CODE REVIEW

**Comment by aashish24** [comment]
@mbertrand this looks great!! It would be awesome if you can add some initial documentation as well. Also, we should have a sprint planning meeting in the new year.

**Comment by aashish24** [comment]
I am okay if you add docs in a separate PR :+1: LGTM

**Comment by mbertrand** [comment]
Sure, will do.

**Comment by mbertrand** [comment]
@aashish24 I added documentation and fixed the Travis build.  However, in order to get tests to pass I could not use girder 1.4.1, because it doesn't include a required change made in https://github.com/girder/girder/pull/1134.  So I modified travis.yml to check out girder at that commit.

**Comment by aashish24** [comment]
LGTM :+1: Thanks!

**Comment by mbertrand** [comment]
Closing without merge, superceded by gaia_api branch

**Pull request closed without merging**
